<?php
$baseHelper = $this->helper('ET\Base\Helper\Data');
$customCss = $baseHelper->getConfigValue('theme_section/custom_settings/custom_css');
$customJs = $baseHelper->getConfigValue('theme_section/custom_settings/custom_js');
?>
<?php if ($customCss != '') { ?>
    <style>
    <?php echo $customCss; ?>
    </style>
<?php } ?>
<?php if ($customJs != '') { ?>
    <script>
        require(['jquery'], function () {
    <?php echo $customJs; ?>
        });
    </script>
<?php } ?>
<?php
$addthisEnable = $baseHelper->getConfigValue('theme_section/addthis/enable');
$pubId = $baseHelper->getConfigValue('theme_section/addthis/pubid');

if ($addthisEnable) {
    ?>
    <div class="addthis_sharing_toolbox"></div>
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?php echo $pubId; ?>" async="async"></script>
<?php } ?>
