<?php
/**
 * Product list template
 *
 * @var $block \Gmc\Catalog\Block\CategoryProducts
 * @var $helper \Gmc\Catalog\Helper\Data
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
//$_productCollection = $block->getCategoryProducts();
$categoryId = $block->getData('category_id');
$products = $block->getCategoryProducts($categoryId);
?>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#tab1">
            <?= $escaper->escapeHtml(__('Collections')) ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#tab2">
            <?= $escaper->escapeHtml(__('Deals')) ?>
        </a>
    </li>
    <!-- Add more tabs as needed -->
</ul>

<div class="tab-content">
    <div id="tab1" class="tab-pane fade show active">
        <?php echo $block->getCategoryProducts($categoryId); ?>
    </div>
    <div id="tab2" class="tab-pane fade">
        <?php //echo $block->getCategoryProducts($categoryId); ?>
    </div>
    <!-- Add more tab content divs as needed -->
</div>
