<?php
/**
 * Product list template
 *
 * @var $block \Gmc\Catalog\Block\CategoryProducts
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$tabOneId = $block->getTabOneId();
$productsTabOne = $block->getCategoryProducts($tabOneId);
?>

<div class="container">
    <main class="mt-3">
        <div class="row">
                <?php foreach ($productsTabOne as $product): ?>
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card">
                        <img src="<?php echo $block->getImageUrl($product, 'thumbnail') ?>" class="card-img-top"
                                     alt="<?php echo $product->getName() ?>" style="object-fit: cover; height: 100%;">
                        <div class="card-body">
                            <h5 class="card-title"><?= $product->getName() ?></h5>
                            <?php
                                $attrs = ['kilometers', 'fuel_type', 'owner', 'seater'];
                                $customAttrs = $block->getListAttributesValue($product, $attrs);
                                ?>
                            <div class="product-attributes">
                                <div class="attribute">
                                    <?php foreach ($customAttrs as $attr): ?>
                                       <span style="background-color: #eee; color: #333; padding: 5px;"><?php echo $attr['value'] ?></span>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <button class="quick-buy-button" style="background-color: #ff6600; color: #fff; padding: 5px;">Quick Buy</button>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </main>
</div>
