<?php 
    $_product = $block->getProduct(); 
    $special_date=$_product->getSpecialToDate();
?>
<?php
        if($special_date && (time()-(60*60*24)) < strtotime($special_date)) {
                ?>
        <div id="product_countdown">
                <div class="group-countdown">
                    <div class="countdown-item"
                         data-timer="<?php echo date("Y/m/d H:i:s", strtotime($special_date)); ?>">
                        <div class="deals-time time-day">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-hours">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-mins">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-secs">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                    </div>
                </div>
        </div>
<?php } ?>

<script>
        require([
            'jquery'
        ], function ($) {
            ;(function (el) {
                var $element = $(el);

                function _countDown(date, id) {
                    var dateNow = new Date();
                    var amount = date.getTime() - dateNow.getTime();
                    delete dateNow;
                    if (amount < 0) {
                        id.html("Now!");
                    } else {
                        var days = 0;
                        hours = 0;
                        mins = 0;
                        secs = 0;
                        out = "";
                        amount = Math.floor(amount / 1000);
                        days = Math.floor(amount / 86400);
                        amount = amount % 86400;
                        hours = Math.floor(amount / 3600);
                        amount = amount % 3600;
                        mins = Math.floor(amount / 60);
                        amount = amount % 60;
                        secs = Math.floor(amount);
                        $(".time-day .num-time", id).text(days);
                        $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day') ?>" : "<?php echo __('Days') ?>"));
                        $(".time-hours .num-time", id).text(hours);
                        $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour') ?>" : "<?php echo __('Hours') ?>"));
                        $(".time-mins .num-time", id).text(mins);
                        $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min') ?>" : "<?php echo __('Mins') ?>"));
                        $(".time-secs .num-time", id).text(secs);
                        $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec') ?>" : "<?php echo __('Secs') ?>"));
                        setTimeout(function () {
                            _countDown(date, id)
                        }, 1000);
                    }
                }

                $(".countdown-item", $element).each(function () {
                    var timer = $(this).data('timer');
                    var data = new Date(timer);
                    _countDown(data, $(this));
                });
            })('#product_countdown');
        });
    </script>