<?php
/**
 * @category BZOTech
 * @package BzoTech_PopupLogin
 * @version 1.0.0
 * @copyright Copyright (c) 2022 BZOTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * @author BZOTech Company  
 *   
 */

/** @var \Magento\Customer\Block\Form\Login $block */

$_config        = $this->helper('BzoTech\PopupLogin\Helper\Data');
$currentPageUrl = $_config->getUrlPage();
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="#"
              method="post"
              id="login-form-popup"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= __('* Required Fields') ?>">
                <div class="field email required">
                    <label class="label" for="mobile_number_login"><span><?= __('Mobile Number') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" name="mobile_number_login"
                        id="mobile_number_login"
                        placeholder="Mobile Number" 
                        data-validate='{"required":true, "minlength":10, "maxlength":10, "validate-number":true}'
                        data-mage-init='{"mage/trim-input":{}}'>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2_login">
                            <span><?= __('Sign In') ?></span></button>
                    </div>
                </div>
            </fieldset>
        </form>

        <?php if (!str_contains($currentPageUrl, 'customer/account/create')) { ?>
            <div class="bottom-popup">
                <div class="sub-title"><?php echo __('Don\'t have an account?') ?></div>
                <div class="trigger-button">
                    <a class="trigger-create" href="javascript:void(0)">
                        <span><?php echo __('Sign Up Now') ?></span>
                    </a>
                </div>
            </div>
        <?php } ?>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form-popup"
                }
            }
        }
    </script>
</div>
<script>
    require(['jquery'], function($) {
        const loginForm = $('#login-form-popup');
        loginForm.submit(function (event) {
            event.preventDefault();
            if (loginForm.valid()) {
                const formData = loginForm.serialize();
                $.ajax({
                    url: '<?php echo $this->getUrl('mobileauth/account/loginpost') ?>',
                    type: 'post',
                    data: formData,
                    dataType: 'json',
                    beforeSend:function(xhr) {
                        $('.submit').attr('disabled', true);
                    },                    
                    success: function (response) {
                        if (response.success === true) {
                            // Login successful, redirect to account page
                            window.location.href = '<?php echo $this->getUrl('customer/account') ?>';
                        } else {
                            // Show error message
                            window.location.reload();
                        }
                    },
                    complete:function(xhr) {
                        $('.submit').attr('disabled', false);
                    }                    
                });
            }            
        });
    });
</script>