<?php
/**
 * @category BZOTech
 * @package BzoTech_PopupLogin
 * @version 1.0.0
 * @copyright Copyright (c) 2022 BZOTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * @author BZOTech Company  
 *   
 */

/** @var \Magento\Customer\Block\Form\Register $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$formData        = $block->getFormData();
$_config         = $this->helper('BzoTech\PopupLogin\Helper\Data');
$currentPageUrl  = $_config->getUrlPage();
?>
<form class="form create account form-create-account"
      action="<?php echo $this->getUrl('mobileauth/account/generateotp') ?>"
      method="post"
      id="form-validate-register"
      enctype="multipart/form-data"
      autocomplete="off"
      data-mage-init='{"validation":{}}'>
    <?= /* @noEscape */
    $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset generate-otp"
              data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field required">
            <label for="mobile_number" class="label"><span><?= $escaper->escapeHtml(__('Mobile Number')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="mobile_number"
                       autocomplete="mobile_number"
                       id="mobile_number"
                       value=""
                       title="<?= $escaper->escapeHtmlAttr(__('Mobile Number')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate='{"required":true, "minlength":10, "maxlength":10, "validate-number":true}'>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset create-account" style="display: none;"
              data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
            <div class="field required">
                <label for="otp" class="label"><span><?= $escaper->escapeHtml(__('OTP Verification')) ?></span></label>
                <div class="control">
                    <input type="text"
                        name="otp"
                        autocomplete="otp"
                        id="otp"
                        value=""
                        title="<?= $escaper->escapeHtmlAttr(__('OTP Verification')) ?>"
                        class="input-text"
                        data-mage-init='{"mage/trim-input":{}}'
                        data-validate='{"required":true,"validate-number":true}'>
                </div>
            </div>        
            <div class="field required">
            <label for="firstname" class="label"><span><?= $escaper->escapeHtml(__('First Name')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="firstname"
                       autocomplete="firstname"
                       id="firstname"
                       value=""
                       title="<?= $escaper->escapeHtmlAttr(__('First Name')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate='{"required":true}'>
            </div>
        </div>
        <div class="field required">
            <label for="lastname" class="label"><span><?= $escaper->escapeHtml(__('Last Name')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="lastname"
                       autocomplete="lastname"
                       id="lastname"
                       value=""
                       title="<?= $escaper->escapeHtmlAttr(__('Last Name')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate='{"required":true}'>
            </div>
        </div>        
    </fieldset>    
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action submit primary"
                    title="<?= $escaper->escapeHtmlAttr(__('Generate OTP')) ?>">
                <span><?= $escaper->escapeHtml(__('Generate OTP')) ?></span>
            </button>
        </div>
    </div>
    <?php if (!str_contains($currentPageUrl, 'customer/account/login')) { ?>
        <div class="back-to-login">
            <a class="back-login trigger-login" href="javascript:void(0)">
                <span><?php echo $escaper->escapeHtml(__('Go to Login')) ?></span>
            </a>
        </div>
    <?php } ?>
</form>
<script>
    require(['jquery'], function($) {
        const registerForm = $('#form-validate-register');
        registerForm.submit(function (event) {
            event.preventDefault();
            if (registerForm.valid()) {
                const formData = registerForm.serialize();
                $.ajax({
                    url: document.getElementById('form-validate-register').action,
                    type: 'post',
                    data: formData,
                    dataType: 'json',
                    beforeSend:function(xhr) {
                        $('.submit').attr('disabled', true);
                    },
                    success: function (response) {
                        if (response.success === true) {
                            if (response.redirect === true) {
                                window.location.href = '<?php echo $this->getUrl('customer/account') ?>';
                            } else {
                                $('.generate-otp').hide();
                                document.getElementById('form-validate-register').action = '<?php echo $this->getUrl('mobileauth/account/createaccount') ?>';
                                $('.submit').html('<span>Register</span>');
                                $('.create-account').show();
                            }
                        } else {
                            // Show error message
                            window.location.reload();
                        }
                    },
                    complete:function(xhr) {
                        $('.submit').attr('disabled', false);
                    }
                });
            }            
        });
    });
</script>