<?php

/**
 * Gmc_Catalog
 *
 * PHP version 8.x
 *
 * @category  PHTML
 * @package   Gmc\Catalog
 * @author    Gmc
 * @copyright 2023 Copyright Gmc
 */

/** @var $block \Magento\Catalog\Product\View */
/** @var $viewModel \Gmc\Catalog\ViewModel\Product\View\Helper */

$viewModel  = $block->getViewModel();
$priceContribution = $viewModel->getPriceContribution();
?>
<div class="price-contribution-form">
    <h3><?= 'Booked '.$priceContribution['contribution_booked'].'%'?></h3>    
    <div class="contribution-booked-bar-container fieldset">
        <progress class="contribution-booked-bar" value="<?= $priceContribution['contribution_booked']?>" max="100"></progress>
    </div>
</div>
