<?php

/**
 * Gmc_Catalog
 *
 * PHP version 8.x
 *
 * @category  PHTML
 * @package   Gmc\Catalog
 * @author    Gmc
 * @copyright 2023 Copyright Gmc
 */

/** @var $block \Magento\Catalog\Product\View */
/** @var $viewModel \Gmc\Catalog\ViewModel\Product\View\Helper */

$viewModel  = $block->getViewModel();
$priceContribution = $viewModel->getPriceContribution();
?>
<div class="price-contribution-form">
    <h3><?= 'Booked '.$priceContribution['contribution_booked'].'%'?></h3>    
    <div class="contribution-booked-bar-container fieldset">
        <progress class="contribution-booked-bar" value="<?= $priceContribution['contribution_booked']?>" max="100"></progress>
    </div>
    <?php if ($priceContribution['allowed_contribution']) : ?>
        <form action="<?php echo $block->getUrl('gmcquote/product/addtocart') ?>" data-mage-init='{"validation": {}}' method="post" id="price-contribution-form">
            <!--<div class="field price-contribution required">
                <label for="" class="label"><span>Enter your Contribution (percentage)</span></label>
                <div class="control">
                    <input type="text" name="contribution_percentage" id="contribution-percentage" class="input-text" data-validate="{'required':true, 'validate-digits':true, 'validate-digits-range':'1-100'}" aria-required="true">
                </div>
            </div>-->
            <input type="hidden" name="product_id" value="<?php echo $block->getProduct()->getId(); ?>">
            <input type="hidden" name="contribution_percentage" id="contribution-percentage" value="">
            <div id="error-msg" class="message error" style="display: none;"></div>
            <div class="contribution-slider-container fieldset">
                <p><label for="" class="label">Amount Contribution Slide (in percentage)</label></p>
                <input type="range" min="0" max="100" value="0" class="slider" id="contribution-slider" data-validate="{'required':true, 'validate-digits':true, 'validate-digits-range':'1-100'}">
            </div>            
            <h3><p id="contribution-amount" style="display: none;"></p></h3>            
            <div class="actions">
                <button type="submit" title="Add Your Contribution" class="action primary" id="price-contribution-button">
                    <span>Book your Contribution</span>
                </button>
            </div>
        </form>
        <script type="text/javascript">
            require([
                'jquery',
                'mage/mage'
            ], function($) {
                "use strict";
                $(document).ready(function() {
                    const contributionSlider = document.getElementById('contribution-slider');
                    contributionSlider.oninput = function() {
                        contributionPercentageSelector.value = this.value;
                        showContributionAmount(this.value)
                    }                    
                    $('#price-contribution-form').on('submit', function(event) {
                        event.preventDefault();
                        var dataForm = $('#price-contribution-form');
                        if (dataForm.valid()) {
                            let priceContribution = contributionPercentageSelector.value;
                            priceContribution = parseInt(priceContribution);
                            if (!Number.isInteger(priceContribution) || (priceContribution <= 0)) {
                                return;
                            }
                            $.ajax({
                                url: '<?= $block->getUrl('gmcquote/product/addtocart'); ?>',
                                type: 'POST',
                                dataType: 'json',
                                data: dataForm.serialize(),
                                showLoader: true,
                                beforeSend: function() {
                                    $('body').trigger('processStart');
                                },
                                success: function(response) {
                                    if (response.success === true) {
                                        window.location.href = response.redirect_url;
                                        return;
                                    }
                                    if (response.message) {
                                        $('#error-msg').html(response.message).show();
                                        $('body').trigger('processStop');
                                    }
                                }
                            });
                        }
                    });
                });                
            });
            //contributionPercentage.addEventListener('input', updateFinalContributionAmount);
            const contributionPercentageSelector = document.getElementById('contribution-percentage');            
            const contributionAmountSelector = document.getElementById('contribution-amount');
            function showContributionAmount(value) {
                contributionAmountSelector.style.display = 'none';                
                //const percentValue = parseInt(e.target.value);
                const percentValue = parseInt(value);
                if (!Number.isInteger(percentValue)) {
                    return;
                }                
                const maxContributionAmount = <?= $priceContribution['max_contribution_price']?>;
                const contributionAmount = parseInt((maxContributionAmount*(value/100)));
                if (!Number.isInteger(contributionAmount) || (contributionAmount > maxContributionAmount)) {
                    return;
                }
                const currencySymbol = "<?= $viewModel->getCurrencySymbol()?>";
                contributionAmountSelector.textContent = 'Contribution Amount ' + currencySymbol + contributionAmount;
                contributionAmountSelector.style.display = 'block';
            }                       
        </script>
    <?php endif; ?>
</div>
