<?php

/**
 * Gmc_Catalog
 *
 * PHP version 8.x
 *
 * @category  PHTML
 * @package   Gmc\Catalog
 * @author    Gmc
 * @copyright 2023 Copyright Gmc
 */

/** @var $block \Magento\Catalog\Product\View */
/** @var $viewModel \Gmc\Catalog\ViewModel\Product\View\Helper */

$viewModel  = $block->getViewModel();
$allowedContributions = $viewModel->getAllowedContributionRange();
?>
<div class="price-contribution">
    <h3>Price Contribution</h3>
    <select name="price_contribution" id="price-contribution" class="form-select form-control" data-validate="{required:true}">
        <option value="">-- Select --</option>
        <?php foreach ($allowedContributions as $key => $label) : ?>
            <option value="<?= $key ?>">
                <?= /* @noEscape */ $block->escapeHtml($label) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
<div class="box-tocart">
    <div class="fieldset">
        <div class="actions">
            <button type="submit" title="Add Your Contribution" class="action primary" id="price-contribution-button">
                <span>Add Your Contribution</span>
            </button>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        "use strict";
        $(document).ready(function() {
            $('#price-contribution-button').on('click', function(event) {
                event.preventDefault();
                let priceContribution = $('#price-contribution').val();
                if (!priceContribution) {
                    return;
                }
                $.ajax({
                    url: '<?= $block->getUrl('gmcquote/product/addtocart'); ?>',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        'product_id': <?= $block->getProduct()->getId(); ?>,
                        'price_contribution': priceContribution
                    },
                    showLoader: true,
                    beforeSend: function() {
                        $('body').trigger('processStart');
                    },
                    success: function(response) {
                        if (response.success) {
                            window.location.href = response.redirect_url;
                            return;
                        }
                        window.location.reload();
                    }
                });
            });
        });
    });
</script>
