<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Pwa
 * @author    Webkul Software Private Limited
 * @copyright  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */


$deviceArray = [
    [
        'name' => 'iPad Pro 10.5',
        'device-width' => '834px',
        'device-height' => '1112px',
        'url' => $block->getIosSplashImage(828, 2224),
        'pixel-ratio' => '2'
    ],
    [
        'name' => 'iPad Mini, Air',
        'device-width' => '768px',
        'device-height' => '1024px',
        'url' => $block->getIosSplashImage(1536, 2048),
        'pixel-ratio' => '2'
    ],
    [
        'name' => '8 Plus, 7 Plus, 6s Plus, 6 Plus',
        'device-width' => '414px',
        'device-height' => '736px',
        'url' => $block->getIosSplashImage(1242, 2208),
        'pixel-ratio' => '3'
    ],
    [
        'name' => '8, 7, 6s, 6',
        'device-width' => '375px',
        'device-height' => '667px',
        'url' => $block->getIosSplashImage(750, 1334),
        'pixel-ratio' => '2'
    ],
    [
        'name' => 'iPad Pro 12.9',
        'device-width' => '1024px',
        'device-height' => '1366px',
        'url' => $block->getIosSplashImage(2048, 2732),
        'pixel-ratio' => '2'
    ],
    [
        'name' => 'iPad Pro 11',
        'device-width' => '834px',
        'device-height' => '1194px',
        'url' => $block->getIosSplashImage(1668, 2388),
        'pixel-ratio' => '2'
    ],
    [
        'name' => 'Xs Max',
        'device-width' => '414px',
        'device-height' => '896px',
        'url' => $block->getIosSplashImage(1242, 2688),
        'pixel-ratio' => '3'
    ],
    [
        'name' => 'Xr',
        'device-width' => '414px',
        'device-height' => '896px',
        'url' => $block->getIosSplashImage(828, 1792),
        'pixel-ratio' => '2'
    ],
    [
        'name' => 'X, Xs',
        'device-width' => '375px',
        'device-height' => '812px',
        'url' => $block->getIosSplashImage(1125, 2436),
        'pixel-ratio' => '3'
    ],
    [
        'name' => '13, 13pro',
        'device-width' => '390px',
        'device-height' => '844px',
        'url' => $block->getIosSplashImage(1170, 2532),
        'pixel-ratio' => '3'
    ],
    [
        'name' => '13pro max',
        'device-width' => '428px',
        'device-height' => '926px',
        'url' => $block->getIosSplashImage(1284,2778),
        'pixel-ratio' => '3'
    ],
];

?>
<meta name="theme-color" content="<?= $block->escapeHtml($block->getThemeColor()); ?>">
<link href="<?= $block->escapeUrl($block->getUrl("pwa/manifest")); ?>" rel="manifest" />

<meta name="apple-mobile-web-app-capable" content="yes">

<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-touch-fullscreen" content="yes" />
<meta name="apple-mobile-web-app-title" content="Expo" />
<meta name="apple-mobile-web-app-status-bar-style" content="default" />

<!--  iPad and iPad mini with @2x display running iOS ≤ 6 -->
<link rel="apple-touch-icon" sizes="144x144" href="<?= /* @noEscape */ $block->getIosIconImage(144, 144)?>">
<!-- iPad and iPad mini with @2x display running iOS 7  -->
<link rel="apple-touch-icon" sizes="152x152" href="<?= /* @noEscape */ $block->getIosIconImage(152, 152)?>">
<!--  iPad and iPad mini with @2x display running iOS 8+ -->
<link rel="apple-touch-icon" sizes="180x180" href="<?= /* @noEscape */ $block->getIosIconImage(180, 180)?>">

<?php
    foreach($deviceArray as $eachDevice){
?>
    <!-- $eachDevice['name']  -->
    <link rel="apple-touch-startup-image"
    media="(device-width: <?= $eachDevice['device-width'];?>) and (device-height: <?= $eachDevice['device-height'];?>) and (-webkit-device-pixel-ratio: <?= $eachDevice['pixel-ratio'];?>)"
    href="<?= /* @noEscape */ $eachDevice['url'];?> ">
<?php } ?>



