<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
/** @var \Magento\Customer\ViewModel\LoginButton $loginButtonViewModel */
$loginButtonViewModel = $block->getData('login_button_view_model');
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= __('Registered Customers') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <div class="actions-toolbar">
            <div class="primary"><button type="submit" class="action login primary open-popup-login" name="send" id="send2" <?php if ($loginButtonViewModel->disabled()): ?> disabled="disabled" <?php endif; ?>><span><?= __('Sign In') ?></span></button></div>
        </div>        
    </div>
</div>
