/**
* Footer 1
*/

.footer-style-1 .text-email a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-1 .call-order .call-phone a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-1 .block-subscribe-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
}

.footer-style-1 .block-subscribe-footer .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

/**
* Footer 2
*/

.footer-style-2 .ft-block .call-order .call-phone a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-2 .ft-block .social-list li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-2 .ft-block .links-footer li a:hover{
color: #<?php echo $themeColor; ?>;
}

.footer-style-2 .footer-bottom address a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-2 .newsletter-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Footer 3
*/

.footer-style-3 .block-subscribe-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-3 .block-subscribe-footer .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.footer-style-3 .footer-bottom address a{
color: #<?php echo $themeColor; ?>;
}

.footer-style-3 .ft-block .social-list li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}