/**
* Header General
*/
.bzo-popup-modal .actions-toolbar .primary button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.megamenu-nav a:hover:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.column-featured .featured-items li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.header-middle .header-links .customer-welcome+.link.authorization-link a{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.header-middle .header-links .customer-welcome+.link.authorization-link a:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

/**
* Header 1
*/
.header-1-style .header-desktop .hd-top-support ul li a:hover,
.header-1-style .header-services > ul > li > a:hover{
color: #<?php echo $themeColor; ?>;
}

.header-1-style .header-services .dropdown-block:hover > a{
color: #<?php echo $themeColor; ?>;
}

.header-1-style .header-bottom .megamenu-nav.horizontal-type .megamenu-items > li:hover > a,
.header-1-style .header-bottom .megamenu-nav.horizontal-type .megamenu-items > li.active > a,
.header-1-style .header-bottom .megamenu-nav.horizontal-type .megamenu-items > li.has-active > a{
color: #<?php echo $themeColor; ?>;
}

.header-1-style .header-bottom .megamenu-nav.horizontal-type .megamenu-items > li > a:before{
background-color: #<?php echo $themeColor; ?>;
}

.header-1-style .hd-cart .minicart-wrapper .action.showcart .counter,
.header-1-style .header-wishlist .count{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.header-1-style .header-services .hd-top-services > li > a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.header-1-style .megamenu-nav .megamenu-items > li > .dropdowm-megamenu.type-megamenu > .middle-level-0 > .megamenu-content-cate > .submenu > li > a{
color: #<?php echo $linkColor; ?>;
}

/* Megashop custom - header 1 */
.header-1-style .header-desktop .hd-top-support ul li.tracking a, 
.header-1-style .header-desktop .top-links .action-switcher span {
    color: #<?php echo $linkHoverColor; ?>;
}
.header-1-style .header-desktop .header-bottom,
.header-1-style .header-desktop .header-center-wrapper .search-header .block-search .action.search,
.header-1-style .header-desktop .header-center-wrapper .right-content .hd-cart .minicart-wrapper:before {
    background-color: #<?php echo $themeColor; ?>;
}
.header-1-style .header-desktop .header-bottom .secondary-megamenu .megamenu-items li.level0 a .cat-name,
.header-1-style .header-desktop .header-center-wrapper .search-header .block-search .action.search span
.header-1-style .header-desktop .header-bottom .megamenu-vertical .megamenu-title {
    color: #<?php echo $textOnThemeColor; ?>;
}
.header-1-style .header-desktop .hd-top-support ul li.tracking a, 
.header-1-style .header-desktop .top-links .action-switcher span,
.header-1-style .header-desktop .header-center-wrapper .right-content .contact-title, 
.header-1-style .header-desktop .header-center-wrapper .right-content .minicart-wrapper .text,
.header-1-style .header-desktop .header-bottom .megamenu-vertical .megamenu-items .level0>a,
.header-1-style .megamenu-vertical .megamenu-nav .megamenu-items>li>.dropdowm-megamenu.type-megamenu>.middle-level-0>.megamenu-content-cate>.submenu>li.level1>a,
.header-1-style .header-desktop .header-bottom .secondary-megamenu .dropdowm-megamenu .column-featured h3 {
    color: #<?php echo $linkOnThemeColor; ?>;
}