.block-tab-home .block-title a,
.block-product-list .block-title a,
.block-home-services .block-title a,
.block-home-choose .block-title a,
.block-home-partner .block-title a{
border: 1px solid #<?php echo $themeColor; ?>;
color: #<?php echo $themeColor; ?>;
}

.block-tab-home .block-title a:hover,
.block-product-list .block-title a:hover,
.block-home-services .block-title a:hover,
.block-home-choose .block-title a:hover,
.block-home-partner .block-title a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-home-partner ul li a:hover{
border-color: #<?php echo $themeColor; ?>;
}

.block-home-services .item .read-more a{
color: #<?php echo $themeColor; ?>;
}

.block-home-services .item:hover{
border-color: #<?php echo $themeColor; ?>;
}

.block-cate-home .category-item .parent-name a{
color: #<?php echo $linkColor; ?>;
}

.block-cate-home .category-item .parent-name a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.nav-1 .owl-theme .owl-nav [class*=owl-]:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.block-product-list .product-item-actions .actions-primary .tocart:hover{
background-color: #<?php echo $themeColor; ?>;
}

.block-product-list .bzotech-slider-list .product-item-info .product-item-name a{
color: #<?php echo $linkColor; ?>;
}

.block-product-list .bzotech-slider-list .product-item-info .product-item-name a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.block-post-home .categories a, .block-post-home .read-more a{
color: #<?php echo $themeColor; ?>;
}

.block-product-list .product-item-info:hover{
border-color: #<?php echo $themeColor; ?>;
}

.block-title-more .block-title a:before{
background-color: #<?php echo $themeColor; ?>;
}

.about-home .about-home-quote{
border-left: 2px solid #<?php echo $themeColor; ?>;
}

.client-slider-home{
border: 2px dashed #<?php echo $themeColor; ?>;
}

.nav-2 .owl-theme .owl-nav [class*=owl-]:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.grid-cats .category-item .parent-image a:before{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.bottom-shopnow a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.instagram-full li a:after{
background-color: #<?php echo $themeColor; ?>;
}

.instagram-full li a:before{
color: #<?php echo $textOnThemeColor; ?>;
}

.nav-3 .owl-theme .owl-nav [class*=owl-]:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-cat-pets .item-inner .parent-name strong a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.full-cat-pets .item-inner .cat-btn:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.full-cat-pets .owl-theme .owl-dots .owl-dot.active span,
.full-cat-pets .owl-theme .owl-dots .owl-dot:hover span{
background-color: #<?php echo $themeColor; ?>;
}

.slider-video .slider-image-info .slider-button a{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.slider-video .slider-image-info .slider-button a:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.slider-info-anim .slider-button a{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.slider-info-anim .slider-button a:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.slideshow-home.slider-video .owl-theme .owl-dots .owl-dot:hover span,
.slideshow-home.slider-video .owl-theme .owl-dots .owl-dot.active span{
background-color: #<?php echo $themeColor; ?>;
}

.header-4-style .block-minicart .amount .price-wrapper:first-child .price
{
    color: #<?php echo $themeColor; ?>;
}
.header-4-style .block-minicart .block-content > .actions > .primary .action.primary {
    background: #<?php echo $themeColor; ?>;
}

.header-4-style .action.primary, .header-4-style .action-primary{
    background: #<?php echo $themeColor; ?>;
}
.block-product-home .product-item-name .product-item-link,
ul.services li .main-title,
.block-tab-home .list-product-tabs .item-tab:hover, 
.block-tab-home .list-product-tabs .item-tab.active
 {
    color: #<?php echo $themeColor; ?>;
}
.block-tab-home .list-product-tabs .item-tab.active.loaded
 {
    color: #<?php echo $textOnThemeColor; ?>;
}
.products-grid .product-item-actions .actions-primary .tocart ,
.block-product-home .bzotech-slider-grid.custom-deals .product-item-actions .actions-primary button ,
.block-tab-home .list-product-tabs .item-tab:first-child,
.block-last-news .item-inner .categories:hover,
.banners .shopnow:hover{
    background: #<?php echo $themeColor; ?>;
}
.block.bzo-categories .categories-listing.grid-categories .category-item .category-info .parent-name a,
.block-product-home .block-title strong.google-element-font,
.product-1-style .products-grid .product-item-name a:hover,
.block-product-home .product-item-name .product-item-link:hover,
.products-grid .price-box .old-price .price,
.block-product-home .bzotech-slider-grid.custom-deals .countdown-item .num-time,
.services .main-title:hover {
    color: #<?php echo $linkOnThemeColor; ?>;
}