/**
* Product 1
*/

.product-1-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
}

.product-1-style .products-grid .product-item-name a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.product-1-style .products-grid .product-item-info:hover .product-item-actions .actions-primary .tocart{
background-color: #<?php echo $themeColor; ?>;
}

.product-1-style .products-grid .product-item-info .product-item-actions .actions-primary .tocart:hover{
background-color: #<?php echo $linkHoverOnThemeColor; ?>;
}

.product-1-style .products-list .product-item-info .actions-primary .tocart:hover{
background-color: #<?php echo $linkHoverOnThemeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-1-style .products-list .product-item-info .product-item-name a:hover{
color: #<?php echo $themeColor; ?>;
}

.product-1-style .products-list .product-item-info .actions-secondary .action:hover,
.product-1-style .products-list .product-item-info .product-reviews-summary .reviews-actions a:hover{
color: #<?php echo $themeColor; ?>;
}

/**
* Product 2
*/

.product-2-style .products-grid .product-item-actions .action:hover{
background-color: #<?php echo $themeColor; ?>;
}

.product-2-style .products-grid .price-box .price,
.product-2-style .products-grid .price-box .special-price .price{
color: #<?php echo $themeColor; ?>;
}

.product-2-style .products-grid .product-item-name a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.product-2-style .products-grid .product-reviews-summary .reviews-actions a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

/**
* Product 3
*/

.product-3-style .products-grid .price-box .old-price .price{
color: #<?php echo $themeColor; ?>;
}

.product-3-style .products-grid .product-item-name a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.product-3-style .products-grid .product-item-actions .action:hover{
background-color: #<?php echo $themeColor; ?>;
}

/**
* Product 4
*/
.product-4-style .product-item .special-price .price, .product-4-style .product-item .minimal-price .price {
    color: #<?php echo $themeColor; ?>;
}