<?php

/**
 * Gmc_Catalog
 *
 * PHP version 8.x
 *
 * @category  PHTML
 * @package   Gmc\Catalog
 * @author    Gmc
 * @copyright 2023 Copyright Gmc
 */

/** @var $block \Magento\Catalog\Category\View */
/** @var $viewModel \Gmc\Catalog\ViewModel\Product\View\Helper */

$viewModel  = $block->getViewModel();
//$priceContribution = $viewModel->getPriceContribution();
?>
<?php echo 'I AM HERE...'; ?>
