<?php
/**
 * Mobile Header Icons
 *
 * @var $block \Gmc\Theme\Block\MobileHeader
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="mobile-sticky-footer">
    <a href="/" class="footer-icon"><i class="fas fa-home"></i> Home</a>
    <a href="/mobileauth/account/register" class="footer-icon"><i class="fas fa-user"></i> Profile</a>
    <a href="/explore" class="footer-icon"><i class="fas fa-search"></i> Explore</a>
    <a href="/checkout/cart/" class="footer-icon"><i class="fas fa-shopping-cart"></i> Cart</a>
</div>
